//! The schema a model is shown for a built-in tool.
//!
//! Built-in schemas are generated by `schemars`, which adds annotations that
//! cost prompt tokens on every request and tell the model nothing it can act
//! on: the draft URL, a type title per struct, Rust integer widths as `format`,
//! `default: null` on every optional field, and LocalPilot's own repair-intent
//! marker. [`advertised_schema`] removes exactly those, and nothing that changes
//! which inputs the schema accepts: nullable unions, `required`, `enum`/`const`,
//! bounds, `additionalProperties`, `$ref` and every non-null default stay as
//! they are. It walks schema positions only, so a property *named* `title` or
//! `default`, or an `enum` value that happens to contain such a key, is never
//! touched. Validation, readable errors and argument repair keep using the
//! tool's full schema; MCP schemas are never rewritten.

use serde_json::{Map, Value};

use crate::schema_intent::INTENT_KEY;

/// `format` values `schemars` emits for Rust numeric types. A string format
/// (`uri`, `date-time`, ...) is a real constraint and is kept.
const GENERATED_NUMERIC_FORMATS: &[&str] = &[
    "uint", "uint8", "uint16", "uint32", "uint64", "int8", "int16", "int32", "int64", "float",
    "double",
];

/// Keywords whose value is a map from names to subschemas.
const SCHEMA_MAPS: &[&str] = &["properties", "patternProperties", "definitions", "$defs"];
/// Keywords whose value is a single subschema.
const SCHEMA_SINGLE: &[&str] = &[
    "items",
    "additionalProperties",
    "additionalItems",
    "not",
    "if",
    "then",
    "else",
    "contains",
    "propertyNames",
];
/// Keywords whose value is a list of subschemas.
const SCHEMA_LISTS: &[&str] = &["oneOf", "anyOf", "allOf", "prefixItems", "items"];

/// The schema to advertise for a built-in tool: `schema` without the generated
/// annotations described in the module docs.
#[must_use]
pub fn advertised_schema(schema: &Value) -> Value {
    clean(schema, true)
}

fn clean(schema: &Value, root: bool) -> Value {
    let Value::Object(object) = schema else {
        // A boolean schema, or anything that is not a schema object.
        return schema.clone();
    };
    let mut out = Map::with_capacity(object.len());
    let numeric = is_numeric(object);
    for (key, value) in object {
        if is_generated_annotation(key, value, root, numeric) {
            continue;
        }
        let cleaned = if SCHEMA_MAPS.contains(&key.as_str()) {
            match value {
                Value::Object(map) => Value::Object(
                    map.iter()
                        .map(|(name, sub)| (name.clone(), clean(sub, false)))
                        .collect(),
                ),
                other => other.clone(),
            }
        } else if SCHEMA_SINGLE.contains(&key.as_str()) && value.is_object() {
            clean(value, false)
        } else if SCHEMA_LISTS.contains(&key.as_str()) && value.is_array() {
            match value {
                Value::Array(items) => {
                    Value::Array(items.iter().map(|sub| clean(sub, false)).collect())
                }
                other => other.clone(),
            }
        } else {
            value.clone()
        };
        out.insert(key.clone(), cleaned);
    }
    Value::Object(out)
}

fn is_generated_annotation(key: &str, value: &Value, root: bool, numeric: bool) -> bool {
    match key {
        "$schema" => root,
        "title" => true,
        "default" => value.is_null(),
        "format" => {
            numeric
                && value
                    .as_str()
                    .is_some_and(|format| GENERATED_NUMERIC_FORMATS.contains(&format))
        }
        _ => key == INTENT_KEY,
    }
}

/// Whether this schema object's `type` admits an integer or a number.
fn is_numeric(object: &Map<String, Value>) -> bool {
    let numeric = |value: &Value| matches!(value.as_str(), Some("integer" | "number"));
    match object.get("type") {
        Some(Value::Array(types)) => types.iter().any(numeric),
        Some(single) => numeric(single),
        None => false,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn generated_annotations_are_removed() {
        let raw = json!({
            "$schema": "http://json-schema.org/draft-07/schema#",
            "title": "ReadFileInput",
            "type": "object",
            "required": ["path"],
            "properties": {
                "path": { "type": "string", "description": "Path.", "x-localpilot-intent": "path" },
                "end_line": {
                    "type": ["integer", "null"],
                    "format": "uint64",
                    "minimum": 0.0,
                    "default": null
                }
            }
        });
        assert_eq!(
            advertised_schema(&raw),
            json!({
                "type": "object",
                "required": ["path"],
                "properties": {
                    "path": { "type": "string", "description": "Path." },
                    "end_line": { "type": ["integer", "null"], "minimum": 0.0 }
                }
            })
        );
    }

    #[test]
    fn structural_keywords_and_real_defaults_are_kept() {
        let raw = json!({
            "type": "object",
            "required": ["mode", "items"],
            "additionalProperties": false,
            "properties": {
                "mode": { "enum": ["a", "b"], "default": "a" },
                "items": { "type": "array", "items": { "$ref": "#/definitions/Item" }, "default": [] },
                "fixed": { "const": 3 },
                "when": { "type": "string", "format": "date-time" },
                "maybe": { "oneOf": [{ "type": "null" }, { "type": "integer", "maximum": 9 }] }
            },
            "definitions": { "Item": { "type": ["string", "null"] } }
        });
        assert_eq!(advertised_schema(&raw), raw);
    }

    #[test]
    fn names_and_instance_values_that_look_like_annotations_are_untouched() {
        let raw = json!({
            "type": "object",
            "properties": {
                "title": { "type": "string" },
                "default": { "type": "string" },
                "$schema": { "type": "string" },
                "x-foo": { "type": "string" },
                "choice": {
                    "enum": [{ "title": "kept", "default": null, "x-localpilot-intent": "kept" }],
                    "const": { "title": "kept" },
                    "examples": [{ "title": "kept" }],
                    "default": { "title": "kept", "default": null }
                }
            },
            "definitions": { "title": { "type": "integer" } }
        });
        assert_eq!(advertised_schema(&raw), raw);
    }

    #[test]
    fn nested_schema_positions_are_cleaned() {
        let raw = json!({
            "oneOf": [{ "title": "A", "type": "object", "properties": { "n": { "format": "uint32", "type": "integer" } } }],
            "items": [{ "title": "First" }],
            "additionalProperties": { "title": "Extra", "type": "string" },
            "definitions": { "D": { "title": "D", "type": "object" } }
        });
        assert_eq!(
            advertised_schema(&raw),
            json!({
                "oneOf": [{ "type": "object", "properties": { "n": { "type": "integer" } } }],
                "items": [{}],
                "additionalProperties": { "type": "string" },
                "definitions": { "D": { "type": "object" } }
            })
        );
    }

    #[test]
    fn a_nested_schema_keyword_is_only_removed_at_the_root() {
        let raw = json!({ "properties": { "p": { "$schema": "x", "type": "string" } } });
        assert_eq!(advertised_schema(&raw), raw);
    }

    #[test]
    fn a_numeric_looking_format_on_a_string_is_kept() {
        let raw = json!({ "properties": { "s": { "type": "string", "format": "int32" } } });
        assert_eq!(advertised_schema(&raw), raw);
    }

    #[test]
    fn boolean_schemas_pass_through() {
        let raw = json!({ "properties": { "anything": true, "nothing": false } });
        assert_eq!(advertised_schema(&raw), raw);
    }
}
